//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO_FOTO
    {
        public int ALF_ID { get; set; }
        public int ALU_ID { get; set; }
        public byte[] ALU_DOC_IMG { get; set; }
        public string ALU_PATH_IMG { get; set; }
        public string ALU_IMG_STRING { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual ALUNO ALUNO { get; set; }
    }
}
