//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINA
    {
        public DISCIPLINA()
        {
            this.CURSO_DISCIPLINA = new HashSet<CURSO_DISCIPLINA>();
            this.PROFESSOR_DISCIPLINA = new HashSet<PROFESSOR_DISCIPLINA>();
        }
    
        public int DIS_ID { get; set; }
        public string DIS_NOME { get; set; }
        public int TIP_CUR_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual ICollection<CURSO_DISCIPLINA> CURSO_DISCIPLINA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<PROFESSOR_DISCIPLINA> PROFESSOR_DISCIPLINA { get; set; }
    }
}
