//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.ALUNO = new HashSet<ALUNO>();
            this.CURSO = new HashSet<CURSO>();
            this.DISCIPLINA = new HashSet<DISCIPLINA>();
            this.PROFESSOR = new HashSet<PROFESSOR>();
            this.SALA = new HashSet<SALA>();
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int EMP_ID { get; set; }
        public string EMP_RAZAO_SOCIAL { get; set; }
        public string EMP_NOME_FANTASIA { get; set; }
        public string EMP_CPF_CNPJ { get; set; }
        public string CEP_NUMERO { get; set; }
        public string EMP_END_LOGRADOURO { get; set; }
        public string EMP_END_NUMERO { get; set; }
        public string EMP_END_COMPLEMENTO { get; set; }
        public string EMP_END_UF { get; set; }
        public string EMP_END_BAIRRO { get; set; }
        public Nullable<int> CID_ID { get; set; }
        public byte[] EMP_LOGO { get; set; }
        public string EMP_PATH_LOGO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<int> EMP_ID_MATRIZ { get; set; }
    
        public virtual ICollection<ALUNO> ALUNO { get; set; }
        public virtual ICollection<CURSO> CURSO { get; set; }
        public virtual ICollection<DISCIPLINA> DISCIPLINA { get; set; }
        public virtual ICollection<PROFESSOR> PROFESSOR { get; set; }
        public virtual ICollection<SALA> SALA { get; set; }
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
