//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esoensinoEntities : DbContext
    {
        public esoensinoEntities()
            : base("name=esoensinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALUNO> ALUNO { get; set; }
        public DbSet<ALUNO_FOTO> ALUNO_FOTO { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<CURSO_DISCIPLINA> CURSO_DISCIPLINA { get; set; }
        public DbSet<DISCIPLINA> DISCIPLINA { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<MATRICULA> MATRICULA { get; set; }
        public DbSet<MATRICULA_TIPO> MATRICULA_TIPO { get; set; }
        public DbSet<PERIODO> PERIODO { get; set; }
        public DbSet<PROFESSOR> PROFESSOR { get; set; }
        public DbSet<PROFESSOR_DISCIPLINA> PROFESSOR_DISCIPLINA { get; set; }
        public DbSet<PROFESSOR_TURMA> PROFESSOR_TURMA { get; set; }
        public DbSet<SALA> SALA { get; set; }
        public DbSet<SERIE> SERIE { get; set; }
        public DbSet<SERIE_TIPO> SERIE_TIPO { get; set; }
        public DbSet<TIPO_CURSO> TIPO_CURSO { get; set; }
        public DbSet<TURMA> TURMA { get; set; }
        public DbSet<TIPO_TURMA> TIPO_TURMA { get; set; }
    }
}
