//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA_TIPO
    {
        public MATRICULA_TIPO()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
        }
    
        public int TIP_MAT_ID { get; set; }
        public string TIP_MAT_DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
    }
}
