//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        public int MAT_ID { get; set; }
        public string MAT_REF { get; set; }
        public Nullable<System.DateTime> MAT_DATA { get; set; }
        public Nullable<int> CUR_ID { get; set; }
        public Nullable<int> TIP_MAT_ID { get; set; }
        public Nullable<int> MAT_ID_ANT { get; set; }
        public Nullable<int> ALU_ID { get; set; }
        public Nullable<int> MAT_ANO_LETIVO { get; set; }
        public Nullable<int> SER_ID { get; set; }
        public Nullable<int> PER_ID { get; set; }
        public Nullable<int> TUR_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual ALUNO ALUNO { get; set; }
        public virtual CURSO CURSO { get; set; }
        public virtual MATRICULA_TIPO MATRICULA_TIPO { get; set; }
        public virtual PERIODO PERIODO { get; set; }
        public virtual SERIE SERIE { get; set; }
        public virtual TURMA TURMA { get; set; }
    }
}
