//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODO
    {
        public PERIODO()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int PER_ID { get; set; }
        public string PER_DESCRICAO { get; set; }
    
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
