//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALA
    {
        public SALA()
        {
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int SAL_ID { get; set; }
        public string SAL_DESCRICAO { get; set; }
        public Nullable<int> SAL_QTDEALUNOS { get; set; }
        public Nullable<bool> SAL_LABORATORIO { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<int> EMP_ID { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
