//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIE
    {
        public SERIE()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int SER_ID { get; set; }
        public int CUR_ID { get; set; }
        public string SER_DESCRICAO { get; set; }
        public int TIP_SERIE_ID { get; set; }
        public int SER_DURACAO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        public virtual SERIE_TIPO SERIE_TIPO { get; set; }
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
