//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIE_TIPO
    {
        public SERIE_TIPO()
        {
            this.SERIE = new HashSet<SERIE>();
        }
    
        public int TIP_SER_ID { get; set; }
        public string TIP_SER_DESCRICAO { get; set; }
    
        public virtual ICollection<SERIE> SERIE { get; set; }
    }
}
