//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_TURMA
    {
        public TIPO_TURMA()
        {
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int TIP_TUR_ID { get; set; }
        public string TIP_TUR_DESCRICAO { get; set; }
    
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
