//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DAL.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURMA
    {
        public TURMA()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
            this.PROFESSOR_TURMA = new HashSet<PROFESSOR_TURMA>();
        }
    
        public int TUR_ID { get; set; }
        public string TUR_NOME { get; set; }
        public int CUR_ID { get; set; }
        public Nullable<int> SER_ID { get; set; }
        public int PER_ID { get; set; }
        public int TUR_ANOLETIVO { get; set; }
        public Nullable<int> TUR_ANOGRADE { get; set; }
        public Nullable<System.DateTime> TUR_DATINI { get; set; }
        public Nullable<System.DateTime> TUR_DATFIM { get; set; }
        public Nullable<int> TUR_QTDEALUNOS { get; set; }
        public int TIP_TUR_ID { get; set; }
        public Nullable<int> SAL_ID { get; set; }
        public int EMP_ID { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        public virtual PERIODO PERIODO { get; set; }
        public virtual ICollection<PROFESSOR_TURMA> PROFESSOR_TURMA { get; set; }
        public virtual SALA SALA { get; set; }
        public virtual SERIE SERIE { get; set; }
        public virtual TIPO_TURMA TIPO_TURMA { get; set; }
    }
}
