//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlunoDTO
    {
        public AlunoDTO()
        {
            this.ALUNO_FOTO = new HashSet<AlunoFotoDTO>();
            this.MATRICULA = new HashSet<MatriculaDTO>();
        }
    
        public int ALU_ID { get; set; }
        public int EMP_ID { get; set; }
        public string ALU_NOME { get; set; }
        public string ALU_CPF_CNPJ { get; set; }
        public string ALU_EMAIL { get; set; }
        public string ALU_NOME_MAE { get; set; }
        public string ALU_NOME_PAI { get; set; }
        public string ALU_RG { get; set; }
        public string ALU_RG_ORGAO { get; set; }
        public Nullable<System.DateTime> ALU_RG_DTEMISSAO { get; set; }
        public string ALU_CEL { get; set; }
        public string ALU_TEL { get; set; }
        public string CEP_NUMERO { get; set; }
        public string ALU_END_LOGRADOURO { get; set; }
        public string ALU_END_NUMERO { get; set; }
        public string ALU_END_COMPLEMENTO { get; set; }
        public string ALU_END_UF { get; set; }
        public string ALU_END_BAIRRO { get; set; }
        public string ALU_END_CIDADE { get; set; }
        public Nullable<int> ALU_GENERO { get; set; }
        public Nullable<System.DateTime> ALU_DTNASCIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual EmpresaDTO EMPRESA { get; set; }
        public virtual ICollection<AlunoFotoDTO> ALUNO_FOTO { get; set; }
        public virtual ICollection<MatriculaDTO> MATRICULA { get; set; }
    }
}
