//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoDisciplinaDTO
    {
        public int CUR_ID { get; set; }
        public int DIS_ID { get; set; }
        public Nullable<int> DIS_CARGA_HORARIA { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual CursoDTO CURSO { get; set; }
        public virtual DisciplinaDTO DISCIPLINA { get; set; }
    }
}
