//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplinaDTO
    {
        public DisciplinaDTO()
        {
            this.CURSO_DISCIPLINA = new HashSet<CursoDisciplinaDTO>();
            this.PROFESSOR_DISCIPLINA = new HashSet<ProfessorDisciplinaDTO>();
        }
    
        public int DIS_ID { get; set; }
        public string DIS_NOME { get; set; }
        public int TIP_CUR_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual ICollection<CursoDisciplinaDTO> CURSO_DISCIPLINA { get; set; }
        public virtual EmpresaDTO EMPRESA { get; set; }
        public virtual ICollection<ProfessorDisciplinaDTO> PROFESSOR_DISCIPLINA { get; set; }
    }
}
