//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESO.ESOESCOLA.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessorDTO
    {
        public ProfessorDTO()
        {
            this.PROFESSOR_DISCIPLINA = new HashSet<ProfessorDisciplinaDTO>();
            this.PROFESSOR_TURMA = new HashSet<ProfessorTurmaDTO>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_NOME { get; set; }
        public string PRO_CPF_CNPJ { get; set; }
        public string CEP_NUMERO { get; set; }
        public string PRO_END_LOGRADOURO { get; set; }
        public string PRO_END_NUMERO { get; set; }
        public string PRO_END_COMPLEMENTO { get; set; }
        public string PRO_END_UF { get; set; }
        public string PRO_END_BAIRRO { get; set; }
        public Nullable<int> CID_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual EmpresaDTO EMPRESA { get; set; }
        public virtual ICollection<ProfessorDisciplinaDTO> PROFESSOR_DISCIPLINA { get; set; }
        public virtual ICollection<ProfessorTurmaDTO> PROFESSOR_TURMA { get; set; }
    }
}
