USE [estoqueloja]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIO](
	[USU_LOGIN] [varchar](80) NOT NULL,
	[USU_NOME] [varchar](70) NULL,
	[USU_SENHA] [varchar](80) NOT NULL,
	[USU_ADMIN] [bit] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[USU_LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USUARIO] ADD  DEFAULT ((0)) FOR [USU_ADMIN]
GO

CREATE TABLE [dbo].[PRODUTO](
	[PRO_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRO_DESCRICAO] [varchar](70) NULL,
	[PRO_VLR_UN] [numeric](18, 2) NULL,
	[PRO_MARGEM_LUCRO] [numeric](18, 2) NULL,
	[PRO_QTD_ESTOQUE] [numeric](18, 2) NULL,
 CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[PRO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LOG](
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRO_ID] [int] NULL,
	[LOG_DESCRICAO] [varchar](400) NULL,
	[LOG_DATA] [datetime] NULL,
	[USU_LOGIN] [varchar](80) NULL,
 CONSTRAINT [PK_LOG] PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOG]  WITH NOCHECK ADD  CONSTRAINT [FK_LOG_PRODUTO] FOREIGN KEY([PRO_ID])
REFERENCES [dbo].[PRODUTO] ([PRO_ID])
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[LOG] CHECK CONSTRAINT [FK_LOG_PRODUTO]
GO

ALTER TABLE [dbo].[LOG]  WITH NOCHECK ADD  CONSTRAINT [FK_LOG_USUARIO] FOREIGN KEY([USU_LOGIN])
REFERENCES [dbo].[USUARIO] ([USU_LOGIN])
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[LOG] CHECK CONSTRAINT [FK_LOG_USUARIO]
GO


