//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTOQUELOJA.DAO.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int LOG_ID { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public string LOG_DESCRICAO { get; set; }
        public Nullable<System.DateTime> LOG_DATA { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
