//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTOQUELOJA.DAO.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.LOG = new HashSet<LOG>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_DESCRICAO { get; set; }
        public Nullable<decimal> PRO_VLR_UN { get; set; }
        public Nullable<decimal> PRO_MARGEM_LUCRO { get; set; }
        public Nullable<decimal> PRO_QTD_ESTOQUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG> LOG { get; set; }
    }
}
